---
title: "<center><strong>Data Science for Economists</strong></center>"
author: "<center>by Grant McDermott</center>"
date: "<center>01: Intro</center>"
output: html_document
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(gapminder)
library(hrbrthemes)
library(gganimate)
library(magick)
library(gifski)

```



```{r}

# regression
fit <- lm(mpg ~ wt, data = mtcars)
summary(fit)

```


```{r}

# plot regression in base R
par(mar = c(4, 4, 1, .1))
plot(mtcars$wt, mtcars$mpg)
abline(fit, col = "red")

```

```{r}

# Same as above, but in ggplot
library(ggplot2)
ggplot(data = mtcars, aes(x = wt, y = mpg)) + 
  geom_smooth(method = "lm", col = "red") + 
  geom_point()

```

```{r}

# the gapminder dataset contains panel data on life expectancy, population size, and GDP per capita for 142 countries since the 1950s
ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp)) + 
  geom_point()

```

```{r}

ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp, size = pop, col = continent)) + 
  geom_point(alpha = 0.3)

```


```{r}

p = ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp))

p + 
  geom_point(alpha = 0.3)  +
  geom_smooth(method = "loess")

```



```{r}

p + 
  geom_point(aes(size = pop, col = continent), alpha = 0.3)  +
  geom_smooth(method = "loess")

```


```{r}

ggplot(data = gapminder) +
  geom_density(aes(x = gdpPercap, fill = continent), alpha=0.3)

```



```{r}

p2 =
  p +
  geom_point(aes(size = pop, col = continent), alpha = 0.3) +
  scale_color_brewer(name = "Continent", palette = "Set1") +
  scale_size(name = "Population", labels = scales::comma) + 
  scale_x_log10(labels = scales::dollar) +
  labs(x = "Log (GDP per capita)", y = "Life Expectancy") + 
  theme_minimal()

p2 + #theme_modern_rc() + 
  geom_point(aes(size = pop, col = continent), alpha = 0.2)

```



```{r}

ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~continent) +
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  ease_aes('linear')

```